services:
  # Spring Boot Backend
  backend:
    build:
      context: ./devoops-deployement
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

  # Angular Frontend  
  frontend:
    build:
      context: ./devoops-deployement-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge